// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortYard.Api.Data;

#nullable disable

namespace PortYard.Api.Migrations
{
    [DbContext(typeof(YardDbContext))]
    partial class YardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortYard.Domain.Entities.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArrivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("CurrentSlotId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DepartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GrossWeightKg")
                        .HasColumnType("int");

                    b.Property<int?>("InboundVesselId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingLine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerNumber")
                        .IsUnique();

                    b.HasIndex("CurrentSlotId");

                    b.HasIndex("InboundVesselId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.CustomsHold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("CustomsHolds");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<int?>("FromSlotRefId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ToSlotRefId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("FromSlotRefId");

                    b.HasIndex("ToSlotRefId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Eta")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Imo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Imo")
                        .IsUnique();

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.YardSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsReeferCapable")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxTeu")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Block", "Row", "Tier")
                        .IsUnique();

                    b.ToTable("YardSlots");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Container", b =>
                {
                    b.HasOne("PortYard.Domain.Entities.YardSlot", "CurrentSlot")
                        .WithMany("Containers")
                        .HasForeignKey("CurrentSlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortYard.Domain.Entities.Vessel", "InboundVessel")
                        .WithMany("InboundContainers")
                        .HasForeignKey("InboundVesselId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentSlot");

                    b.Navigation("InboundVessel");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.CustomsHold", b =>
                {
                    b.HasOne("PortYard.Domain.Entities.Container", "Container")
                        .WithMany("CustomsHolds")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Movement", b =>
                {
                    b.HasOne("PortYard.Domain.Entities.Container", "Container")
                        .WithMany("Movements")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortYard.Domain.Entities.YardSlot", "FromSlot")
                        .WithMany()
                        .HasForeignKey("FromSlotRefId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortYard.Domain.Entities.YardSlot", "ToSlot")
                        .WithMany()
                        .HasForeignKey("ToSlotRefId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Container");

                    b.Navigation("FromSlot");

                    b.Navigation("ToSlot");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Container", b =>
                {
                    b.Navigation("CustomsHolds");

                    b.Navigation("Movements");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Vessel", b =>
                {
                    b.Navigation("InboundContainers");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.YardSlot", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
