// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortYard.Api.Data;

#nullable disable

namespace PortYard.Api.Migrations
{
    [DbContext(typeof(YardDbContext))]
    partial class YardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PortYard.Domain.Entities.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DepartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrossWeightKg")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InboundVesselId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShippingLine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerNumber")
                        .IsUnique();

                    b.HasIndex("CurrentSlotId");

                    b.HasIndex("InboundVesselId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.CustomsHold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("CustomsHolds");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromSlotRefId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToSlotRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("FromSlotRefId");

                    b.HasIndex("ToSlotRefId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Eta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Imo")
                        .IsUnique();

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.YardSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReeferCapable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTeu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Block", "Row", "Tier")
                        .IsUnique();

                    b.ToTable("YardSlots");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Container", b =>
                {
                    b.HasOne("PortYard.Domain.Entities.YardSlot", "CurrentSlot")
                        .WithMany("Containers")
                        .HasForeignKey("CurrentSlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortYard.Domain.Entities.Vessel", "InboundVessel")
                        .WithMany("InboundContainers")
                        .HasForeignKey("InboundVesselId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentSlot");

                    b.Navigation("InboundVessel");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.CustomsHold", b =>
                {
                    b.HasOne("PortYard.Domain.Entities.Container", "Container")
                        .WithMany("CustomsHolds")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Movement", b =>
                {
                    b.HasOne("PortYard.Domain.Entities.Container", "Container")
                        .WithMany("Movements")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortYard.Domain.Entities.YardSlot", "FromSlot")
                        .WithMany()
                        .HasForeignKey("FromSlotRefId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortYard.Domain.Entities.YardSlot", "ToSlot")
                        .WithMany()
                        .HasForeignKey("ToSlotRefId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Container");

                    b.Navigation("FromSlot");

                    b.Navigation("ToSlot");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Container", b =>
                {
                    b.Navigation("CustomsHolds");

                    b.Navigation("Movements");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.Vessel", b =>
                {
                    b.Navigation("InboundContainers");
                });

            modelBuilder.Entity("PortYard.Domain.Entities.YardSlot", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
